[http]

    [http.routers]

      [http.routers.webapp-router]
          rule = "Host(`webapp.local`)"
          #rule = "Host(`codecarbon.local`)"
          service = "webapp-service"
          entrypoints=["web","websecure"]
          priority = 10

    [http.services]
      [http.services.webapp-service.loadbalancer]
          [[http.services.webapp-service.loadbalancer.servers]]
            url = "http://host.docker.internal:3000"
