"""add water_consumed

Revision ID: bff0c550df5f
Revises: 3212895acafd
Create Date: 2026-03-06 14:47:25.205602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bff0c550df5f'
down_revision = '3212895acafd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emissions', sa.Column('water_consumed', sa.Float(), nullable=False))
    op.drop_constraint(op.f('memberships_user_id_fkey'), 'memberships', type_='foreignkey')
    op.drop_constraint(op.f('memberships_organization_id_fkey'), 'memberships', type_='foreignkey')
    op.create_foreign_key(None, 'memberships', 'organizations', ['organization_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'memberships', 'users', ['user_id'], ['id'], ondelete='cascade')
    op.alter_column('project_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'organization_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.alter_column('project_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.create_foreign_key(op.f('memberships_organization_id_fkey'), 'memberships', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('memberships_user_id_fkey'), 'memberships', 'users', ['user_id'], ['id'])
    op.drop_column('emissions', 'water_consumed')
    # ### end Alembic commands ###
