import os
import re
import shutil
import subprocess
import sys
import time
from functools import lru_cache
from typing import Dict

import numpy as np

from codecarbon.core.util import detect_cpu_model
from codecarbon.external.logger import logger


@lru_cache(maxsize=1)
def is_powermetrics_available() -> bool:
    try:
        ApplePowermetrics()
        return _has_powermetrics_sudo()
    except Exception as e:
        logger.debug(
            "Not using PowerMetrics, an exception occurred while instantiating"
            + f" Powermetrics : {e}",
        )
        return False


def clear_powermetrics_cache() -> None:
    is_powermetrics_available.cache_clear()


def _kill_process(process: subprocess.Popen) -> None:
    """
    Kill a Powermetrics subprocess, tolerating a failure to do so.

    The command runs through `sudo`, so the child may be owned by root and
    refuse our signal. Letting that raise would replace the timeout we are
    handling with a PermissionError, and waiting on it without a bound would
    hang for as long as the child lives.
    """
    try:
        process.kill()
        process.wait(timeout=1)
    except (OSError, subprocess.SubprocessError):
        logger.debug("Could not kill the Powermetrics process.")
    finally:
        for stream in (process.stdout, process.stderr):
            if stream is not None:
                stream.close()


def _has_powermetrics_sudo() -> bool:
    if shutil.which("sudo") is None:
        logger.debug("sudo not available, we won't use Apple PowerMetrics.")
        return False
    if shutil.which("powermetrics") is None:
        logger.info(
            "Apple PowerMetrics not available. Please install it if you are using an Apple product."
        )
        return False

    # No context manager here: Popen.__exit__ would wait() without a timeout,
    # which is exactly the hang we are trying to avoid when the kill fails.
    process = subprocess.Popen(
        [
            "sudo",
            "powermetrics",
            "--samplers",
            "cpu_power",
            "-n",
            "1",
            "-i",
            "1",
            "-o",
            "/dev/null",
        ],
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    deadline = time.time() + 3
    while process.poll() is None and time.time() < deadline:
        time.sleep(0.05)
    if process.poll() is None:
        logger.debug("PowerMetrics sudo check timed out.")
        _kill_process(process)
        return False
    _, stderr = process.communicate()

    if re.search(r"[sudo].*password", stderr):
        logger.debug("""Not using PowerMetrics, sudo password prompt detected.
                If you want to enable Powermetrics please modify your sudoers file
                as described in :
                https://docs.codecarbon.io/latest/explanation/methodology/#power-usage
            """)
        return False
    if process.returncode != 0:
        raise Exception("Return code != 0")

    return True


class ApplePowermetrics:
    """
    A class to interact with and retrieve power metrics on Apple Silicon devices using
    the `powermetrics` command-line tool.

    Methods:
    --------
    __init__(output_dir: str = ".", n_points=10, interval=100, log_file_name="powermetrics_log.txt"):
        Initializes the ApplePowermetrics instance, setting up the log file path, system info,
        and other configurations.

    get_details() -> Dict:
        Parses the log file generated by `powermetrics` and returns a dictionary containing
        the average CPU and GPU power consumption and energy deltas. If parsing fails, logs
        the exception and returns an empty dictionary.

    start() -> None:
        Placeholder method for starting the energy reading process (to be implemented).
    """

    _osx_silicon_exec = "powermetrics"

    def __init__(
        self,
        output_dir: str = ".",
        n_points=10,
        interval=100,
        log_file_name="powermetrics_log.txt",
    ):
        self._log_file_path = os.path.join(output_dir, log_file_name)
        self._system = sys.platform.lower()
        self._n_points = n_points
        self._interval = interval
        self._setup_cli()

    def _setup_cli(self) -> None:
        """
        Setup cli command to run Powermetrics
        """
        if self._system.startswith("darwin"):
            cpu_model = detect_cpu_model()
            if cpu_model.startswith("Apple"):
                if shutil.which(self._osx_silicon_exec):
                    self._cli = self._osx_silicon_exec
                else:
                    raise FileNotFoundError(
                        f"Powermetrics executable not found on {self._system}"
                    )
        else:
            raise SystemError("Platform not supported by Powermetrics")

    def _log_values(self) -> bool:
        """
        Logs output from Powermetrics to a file

        :return: False when the command did not run, so that the caller knows
                 the log file was not refreshed and still holds the previous
                 measure.
        """
        if not self._system.startswith("darwin"):
            return False

        # Run the powermetrics command with sudo and capture its output
        cmd = [
            "sudo",
            "powermetrics",
            "-n",
            str(self._n_points),
            "",
            "--samplers",
            "cpu_power",
            "--format",
            "csv",
            "-i",
            str(self._interval),
            "-o",
            self._log_file_path,
        ]
        # _n_points samples of _interval ms is the nominal runtime of the
        # command. Double it to absorb sampler overhead and scheduling jitter,
        # and add a floor so short configurations keep a usable margin. This is
        # a heuristic: it only has to be loose enough that a healthy run never
        # trips it, because its only job is to bound a hang.
        timeout = self._n_points * self._interval / 1000 * 2 + 5
        # DEVNULL so that sudo gets EOF and fails fast instead of blocking
        # forever on a password prompt when it has no cached credential.
        # No context manager: Popen.__exit__ would wait() without a timeout.
        process = subprocess.Popen(
            cmd, universal_newlines=True, stdin=subprocess.DEVNULL
        )
        try:
            returncode = process.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            logger.warning(
                f"Powermetrics did not complete within {timeout:g} seconds, "
                "skipping this measure."
            )
            _kill_process(process)
            return False

        if returncode != 0:
            logger.warning(
                "Returncode while logging power values using "
                + f"Powermetrics: {returncode}"
            )
        return True

    def get_details(self) -> Dict:
        """
        Fetches the CPU Power Details by fetching values from a logged csv file
        in _log_values function
        """
        if not self._log_values():
            return dict()
        details = dict()
        try:
            with open(self._log_file_path) as f:
                logfile = f.read()
            cpu_pattern = r"CPU Power: (\d+) mW"
            cpu_power_list = re.findall(cpu_pattern, logfile)

            details["CPU Power"] = np.mean(
                [float(power) / 1000 for power in cpu_power_list]
            )
            details["CPU Energy Delta"] = np.sum(
                [
                    (self._interval / 1000) * (float(power) / 1000)
                    for power in cpu_power_list
                ]
            )
            gpu_pattern = r"GPU Power: (\d+) mW"
            gpu_power_list = re.findall(gpu_pattern, logfile)
            details["GPU Power"] = np.mean(
                [float(power) / 1000 for power in gpu_power_list]
            )
            details["GPU Energy Delta"] = np.sum(
                [
                    (self._interval / 1000) * (float(power) / 1000)
                    for power in gpu_power_list
                ]
            )
        except Exception as e:
            logger.info(
                f"Unable to read Powermetrics logged file at {self._log_file_path}\n \
                Exception occurred {e}",
                exc_info=True,
            )
        return details

    def start(self) -> None:
        # TODO: Read energy
        pass
