name: Upload to PyPi
on: [workflow_dispatch]
jobs:
    build-package:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
              python-version: 3.8
        # - name: Check versions
        #   run: |
        #       pip install -U pip requests
        #       python3 .github/check_version.py
        - name: Build pip package
          run: |
              python3 -m pip install --upgrade build twine
              python3 -m build
        - name: Archive Pypi artifacts
          uses: actions/upload-artifact@v1
          with:
              name: pypi_dist
              path: dist
        - name: Upload the package to PyPi
          run: twine upload dist/* --username __token__ --password $PYPI_TOKEN
